FROM ubuntu:14.04
LABEL Oraclize = "info@Oraclize.it"

RUN apt-get update && apt-get -y install python -minimal
CMD /usr/bin/python -c "cert={"requesterPubAddress": "0x7b3B54331E83806f7D958b01fF8a68D265E6E390","productID": "PGH101","productDescription": "Fresh Tomatoes","requesterSig": "0x419bhshnbd","origin": "China"}; print(cert['requesterPubAds